<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Monthly Sales Report</title>
    <style>
        /* CSS KHUSUS PDF (Desain Hemat Tinta & Resmi)
           Kita pakai CSS native di head supaya terbaca sempurna oleh DomPDF 
        */
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            color: #111;
            background-color: #fff; /* Wajib Putih Bersih */
            line-height: 1.4;
        }

        /* HEADER */
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 3px double #8B0000; /* Garis ganda merah (Signature CoreLogic) */
            padding-bottom: 15px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: #000;
        }
        .company-name span { color: #8B0000; } /* Aksen Merah dikit aja */
        
        .report-title {
            font-size: 16px;
            font-weight: bold;
            margin-top: 10px;
            text-transform: uppercase;
            border: 1px solid #000;
            display: inline-block;
            padding: 5px 15px;
        }

        .meta-info {
            margin-top: 10px;
            font-size: 11px;
            color: #444;
        }

        /* TABEL DATA */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f0f0f0; /* Abu-abu sangat muda (Hemat Tinta) */
            color: #000;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
            padding: 10px 5px;
            border: 1px solid #888;
            text-align: left;
        }
        td {
            padding: 8px 5px;
            border: 1px solid #888;
            font-size: 11px;
        }
        
        /* Helpers */
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .font-bold { font-weight: bold; }
        
        /* SUMMARY BOX (Kanan Bawah) */
        .summary-container {
            width: 100%;
            margin-top: 25px;
            border: 2px solid #333;
            padding: 15px;
            background-color: #fff;
        }
        .summary-row {
            display: table;
            width: 100%;
            border-bottom: 1px dashed #ccc;
            padding-bottom: 8px;
            margin-bottom: 8px;
        }
        .summary-row span {
            display: table-cell;
        }
        .summary-row .label {
            text-align: left;
            width: 60%;
        }
        .summary-row .value {
            text-align: right;
            width: 40%;
        }
        .grand-total {
            font-size: 16px;
            font-weight: bold;
            color: #8B0000;
            border-top: 2px solid #333;
            padding-top: 10px;
            margin-top: 5px;
            display: table;
            width: 100%;
        }
        .grand-total span {
            display: table-cell;
        }
        .grand-total .label {
            text-align: left;
            width: 60%;
        }
        .grand-total .value {
            text-align: right;
            width: 40%;
        }

        /* FOOTER HALAMAN */
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            font-size: 9px;
            text-align: center;
            color: #777;
            border-top: 1px solid #ccc;
            padding-top: 10px;
        }
    </style>
</head>
<body>

    <div class="header">
        <div class="company-name">CoreLogic <span>Defense Solutions</span></div>
        <div class="report-title">Monthly Sales Report</div>
        <div class="meta-info">
            Period: <strong>{{ DateTime::createFromFormat('!m', $month)->format('F') }} {{ $year }}</strong><br>
            Generated By: Administrator System | Date: {{ date('d F Y') }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="5%" class="text-center">No</th>
                <th width="15%">Date</th>
                <th width="20%">Client Name</th>
                <th width="15%">Unit Type</th>
                <th width="25%">Service Detail</th>
                <th width="20%" class="text-right">Amount (USD)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($orders as $index => $order)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $order->created_at->format('d/m/Y') }}</td>
                <td class="font-bold">{{ $order->user->name }}</td>
                <td>
                    @if(str_contains($order->service->name, 'Combat')) Combat
                    @elseif(str_contains($order->service->name, 'K9')) K9 Unit
                    @elseif(str_contains($order->service->name, 'VIP')) VIP Escort
                    @else Security
                    @endif
                </td>
                <td>{{ $order->service->name }}</td>
                <td class="text-right font-bold">
                    ${{ number_format($order->total_price, 2) }}
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6" class="text-center" style="padding: 20px; font-style: italic;">
                    No sales data found for this period.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary-container">
        <div class="summary-row">
            <span class="label">Total Transactions:</span>
            <span class="value">{{ $orders->count() }} Orders</span>
        </div>

        <div class="summary-row">
            <span class="label">Report Status:</span>
            <span class="value" style="color: green; font-weight: bold;">VERIFIED</span>
        </div>

        <div class="grand-total">
            <span class="label">TOTAL REVENUE:</span>
            <span class="value">${{ number_format($monthlyRevenue, 2) }}</span>
        </div>
    </div>

    <div class="footer">
        CONFIDENTIAL DOCUMENT - FOR INTERNAL USE ONLY<br>
        CoreLogic Defense Solutions &copy; {{ date('Y') }}. Sector 7, Jakarta.
    </div>

</body>
</html>